### ISSUE TITLE
Transfer script fails on msgpack.exceptions.ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by BenoitDalFerro** [bminixhofer/zett#12]
All install requirement satisfied as per repo readme except jax[cuda12]==0.4.23 which is now jax[cuda12]==0.4.38

git clone https://huggingface.co/benjamin/zett-hypernetwork-xlm-roberta-base

```
python3 scripts/transfer.py \
    --target_model=FacebookAI/xlm-roberta-base \
    --tokenizer_name=gpt2 \
    --output=my-new-fancy-xlm-r \
    --model_class=AutoModelForMaskedLM \
    --lang_code=en \
    --checkpoint_path=zett-hypernetwork-xlm-roberta-base \
    --save_pt # otherwise saves only Flax weights
```

> Traceback (most recent call last):
>   File "/mnt/c/users/benoi/dropbox/boite/unbias/produits/débiaiseur/soft/github/UnBias-Vampire-NeMo/zett/scripts/transfer.py", line 148, in <module>
>     hypernet_params = serialization.msgpack_restore(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benoit/miniconda3/envs/zett2/lib/python3.11/site-packages/flax/serialization.py", line 431, in msgpack_restore
>     state_dict = msgpack.unpackb(
>                  ^^^^^^^^^^^^^^^^
>   File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
> msgpack.exceptions.ExtraData: unpack(b) received extra data.

**Comment by tabaochoke** [comment]
The error occurs because the file flax_model.msgpack in your zett-hypernetwork-xlm-roberta-base directory is not the actual model file. Instead, it's a Git LFS pointer file.You need to download the actual large model file from Git LFS. Here is how you can do it.
1. Install Git LFS. For Debian/Ubuntu: If you don't have it, install it on your system. `sudo apt-get install git-lfs`. For other systems, please refer to the official [Git LFS installation guide](https://git-lfs.com/).
3. Initialize Git LFS. Run this command once per user account. `git lfs install`.
4. Pull the LFS files. Navigate to the repository directory (zett-hypernetwork-xlm-roberta-base or the parent project directory) in your terminal and run: `git lfs pull`.This command will read the pointer files and download the actual large files they point to. After running it, the flax_model.msgpack file will contain the correct binary model data, and your script should run without the msgpack error.
